---
driver:
  name: vagrant

provisioner:
  product_name: chef

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[imagr::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
