---
driver:
  name: vagrant
  provider: parallels
  box: apex/macos-10.13.4
  box_check_update: true

provisioner:
  product_name: chef
  install_strategy: always

verifier:
  name: inspec
  inspec_tests:
    - test/integration/default

platforms:
  - name: ubuntu-16.04
    driver:
      box: ubuntu-16.04

  - name: highsierra-chef13
    provisioner:
      product_version: 13

  - name: highsierra-chef14
    provisioner:
      product_version: 14

suites:
  - name: default
    run_list:
      - recipe[imagr::default]
    excludes:
      - ubuntu-16.04
