---
driver:
  name: vagrant

provisioner:
  always_update_cookbooks: true
  install_strategy: once
  product_name: chef
  product_version: latest

verifier:
  name: inspec
  inspec_tests:
    - test/smoke/default

platforms:
  - name: ubuntu-16.04
    run_list:
      - recipe[imagr::default]

suites:
  - name: chef-13
    provisioner:
      product_version: 13
  - name: chef-14
    provisioner:
      product_version: 14
