name 'imagr'
maintainer 'Eric Hanko'
maintainer_email 'eric.hanko1@gmail.com'
license 'MIT'
description 'Installs/Configures imagr'
long_description 'Installs/Configures imagr'
version '0.2.0'
chef_version '~> 13' if respond_to?(:chef_version)
source_url 'https://github.com/americanhanko/imagr-cookbook'
issues_url 'https://github.com/americanhanko/imagr-cookbook/issues'
supports 'ubuntu'
